import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:aplikasi_berita_b/domain/entities/article.dart';
import 'package:aplikasi_berita_b/domain/usecases/get_headline_bussiness_articles.dart';
import 'package:aplikasi_berita_b/domain/usecases/get_top_headline_articles.dart';
part 'article_list_event.dart';
part 'article_list_state.dart';
part 'article_top_headline_list_bloc.dart';
part 'article_headline_bussiness_list_bloc.dart';
